### ISSUE TITLE
Suggestion and enhancement

### ISSUE THREAD

**Issue by DhinagaranDhina** [coding-beagle/ctkeasyedit#1]
**Suggestion**
- Edit window is getting duplicate if user double clicked on the specific widgets ( better override the same window instead of seperate window)
- widgets internal name is counted for all the widgets. ( better count the widgets based on the widgets type. if the selected widget is button then the next button only should consider the internal variable as "button 1")

**Enhance**
- provide the option to select the theme
- button is widely used to trigger/call the function. include the command paramter in it
- seems user should build frame first followed by other widgets. why don't you provide the option to bring the frame to back or front. ? so that user can change the button from one frame to another frame or where ever needed.

**Comment by coding-beagle** [comment]
Thanks for the suggestions.

All of the suggestions except for the button command parameter is uploaded to the latest commit. I like the idea of having command parameter, but I have to restructure the boilerplate generation so this is something I'll work on for the next update.

**Comment by DhinagaranDhina** [comment]
thankss for considering the suggesstion. i feels that the app consumes more time compare to older version. 

minor issue :
- please add CTKColorPicker package in requirment.txt ( faced module not found error )
- when i try to reselect the app images, path is not found.(older path is not overridden by new selected path location)
- optionmenu is not accessible, if we do either one layer up or down then only it shows the optionmenu dropdown

enhancement :
- if possible please provide the widgets hover effect features
- since frame and master root is dark color, could you provide the border color for frame ?
-  the callback function is applicable for whereever is clicked right ? option menu, radio button 

widget :
- could you include more widgets like tab view, table view, segmented button, scrollable frame etc
- tkinter has superb features, show the data in hierarchy, tree view but i could see those widgets not available in ctk, can you include those widgets in this app

**Comment by coding-beagle** [comment]
Hello, 

I've added the following in the latest release:

- Updated requirements.txt to have CTKColorPicker
- Fixed the issues with path not being overwritten
- Fixed the issues with optionmenu widget
- Added a lot more customisation options for widgets.

The rest I'll work on soon. The widgets that are currently not included are because of an issue with the drag binding, but I'll aim to get this updated over the week.

**Comment by DhinagaranDhina** [comment]
Absolutely fantastic! This project is reaching extraordinary heights. When can we expect the next version to be released? Eagerly awaiting its arrival!

**Comment by mctinker** [comment]
Feature request: Ability to resize/expand the application window dynamically as widgets are being added/removed.
 
When first building a GUI, then the overall window size is somewhat unknown.  As more elements are added, it is often necessary to expand the window.  Likewise, when removing elements, the window can shrink.

**Comment by coding-beagle** [comment]
@mctinker Just added in the latest update. Hope it suits your needs.
